# Generated by Django 6.0 on 2026-01-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_ANALYSIS', 'Under Analysis'), ('ACCEPTED', 'Accepted'), ('REFUSED', 'Refused')], default='RECEIVED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('PARCEL_DAMAGED', 'Parcel Damaged'), ('DELIVERY_DELAYED', 'Delivery Delayed'), ('ADDRESS_ERROR', 'Address Error'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_RESOLUTION', 'In Resolution'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=50)),
                ('date_occurred', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incident_photos/')),
            ],
        ),
    ]
