# Generated by Django 6.0 on 2026-01-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('geographic_zone', models.CharField(blank=True, max_length=100)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_rate_per_kg', models.DecimalField(decimal_places=2, help_text='Cost per KG', max_digits=10)),
                ('volume_rate_per_m3', models.DecimalField(decimal_places=2, help_text='Cost per cubic meter', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('CAR', 'Car')], max_length=20)),
                ('capacity_kg', models.PositiveIntegerField(help_text='capacity in kilograms')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, help_text='liters per 100km', max_digits=5)),
                ('is_in_service', models.BooleanField(default=True)),
            ],
        ),
    ]
