# Generated by Django 6.0 on 2026-01-04 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('logistics', '0002_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='logistics.destination'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='logistics.destination'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='shipping.shipment'),
        ),
        migrations.AddField(
            model_name='tour',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.driver'),
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicle'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.tour'),
        ),
    ]
